name: BlockUpdate
author: SBS (Mynet, Salmon, Landy)
description: A BlockUpdate plugin that disables blockupdate
main: blockupdate\Main
version: 1.0
api: 
- 2.0.0
- 2.1.0
- 3.0.0
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 4.0.0
