name: BlockUpdate
author: MyNET
description: A BlockUpdate plugin that make block stand still
main: blockupdate\Main
version: 1.3
api: 
- 3.0.0
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
